### ISSUE TITLE
If git-scm is installed as 'bash only' then status icon fails

### ISSUE THREAD

**Issue by PhilipOakley** [vinsworldcom/nppGitSCM#10]
Only just started trying the nppGitSCM plug-in. I have my git installed as bash-only, rather than the integrated (mixed) shell system.

If I click the `status` (three bars) icon I get that the cmd.exe reports "The code execution cannot proceed because libintl-8.dll was not found. ...". (and repeats for the other .dll's). `diff`, `log` and `blame` do the same.

Git gui and gitk work; Git prompt gives the powershell window.

I thought it worth mentioning should it be something that can be detected and resolved.

**Comment by PhilipOakley** [comment]
Extra info. The failure is often happening for `.c` and `.h` files but appears to work for `.txt` files. 
Not quite worked out a clean pattern.

**Comment by vinsworldcom** [comment]
> git installed as bash-only, rather than the integrated (mixed) shell

Not sure what that means, but the inner workings use CreateProcess() to build the Git command string from `cmd.exe` and adding `pause` to leave the window open, otherwise it just flashes open and closes when done.  I suspect the "bash" only may be your issue.  

libintl-8.dll is in your Git directory:

git/mingw64/bin/libintl-8.dll

and that should be in your Windows PATH environment variable according to the README.  Do you have TortoiseGit installed?  You don't *need* it, but I think it makes for a far more pleasant GUI experience and calling TortoiseGit may "mask" the issues you're having with calling Git from the "bash-only" install.

Cheers.

**Comment by PhilipOakley** [comment]
I'm away at present without access to my Win10 machine. 
I do know that GfW does have a two step `git.exe` process to set up various aspects of the terminal interaction that may be part of the problem.

**Comment by vinsworldcom** [comment]
Examining https://www.stanleyulili.com/git/how-to-install-git-bash-on-windows/, I now understand what "bash-only" means and that will not work with this plugin.  The README explicitly says Git needs to be in your Windows `PATH` environment variable and in the screenshot from the above link, the "Recommended" option puts Git in Windows `PATH` so third-party tools (i.e., Notepad++ and this plugin) can use it.

Cheers.
