### ISSUE TITLE
Replace the git blame with a GitGUI Blame

### ISSUE THREAD

**Issue by k10blogger** [vinsworldcom/nppGitSCM#19]
Before raising a PR.

Wondering why we cannot use git gui for the "Git blame" of the file.

If we provide it as an option in the setting it would look something like this.

A select GUI option in the setting
![image](https://github.com/user-attachments/assets/b5df2a53-a025-4a12-a3a5-5f83a55fd754)

Then when git blame is selected a popup would open as below:
![image](https://github.com/user-attachments/assets/a978946d-4e66-465f-96dc-37191cc9dc50)

Though i would like to replace the git blame with a git gui blame completely and not have the select option as in the setting above.

**Comment by vinsworldcom** [comment]
I was not aware git-gui had that feature.  I use the graphical UI by using TortoiseGit, which has a graphical blame and all the other graphical interfaces for the Git commands this plugin offers.  If you don't use TortoiseGit, the plugin with just `git` for Windows is a pretty bare-bones experience.

![image](https://github.com/user-attachments/assets/9039b90e-3453-41b0-af0a-33e8919ccff7)


I like the idea of a setting checkbox like your mock-up, though the text should read "Blame with Git-GUI", not "Run ...".

What is the "Run in WSL" checkbox you have?

If you do a pull request, please raise it against my 'develop' branch, not the 'main' branch.

Cheers.

**Comment by k10blogger** [comment]
The run in wsl runs all the above git commands in the WSL environment. That is like having a WSL mount on the notepad++ and associated terminal with it. Similar to what VSCode has. Though it is not that useful to many. As i am currently moving away from wsl to docker so currently working on replacing that with "Attach to docker" that would allow these commands to run in the docker environments. 

I raised a PR against develop. Do take a look let me know something needs to be changed or refined.

**Comment by vinsworldcom** [comment]
@k10blogger : I merged your pull request.  Made a few naming updates to stay with my coding style.  The only real issue is the additional logic of the "-gui blame --line=" command needed to be moved from the actual ExecCommand() to the `blameFileFiles()` function.

Tested and this works for me.  **NOTE:** 'Use TortoiseGit' must be disabled; otherwise, TortoiseGit Blame is used for blame (as well as all other TortoiseGit commands are used for their respective actions).  

This issue will auto close when I merge develop branch into main.  Please have a look at the artifact and see if it runs for you:

https://github.com/vinsworldcom/nppGitSCM/actions/runs/11622058753

**NOTE:** the version number has been bumped to 1.4.10.1 in preparation for the new release once merged to main (after you test).

Cheers.

**Comment by k10blogger** [comment]
@vinsworldcom the artifact in the url is working for me as well. 
![image](https://github.com/user-attachments/assets/d55c2a75-c7ab-4ccb-9a43-0a40f09da8e9)
